CREATE TABLE aws_arg (
    id SERIAL PRIMARY KEY,
    station_id VARCHAR(255) NOT NULL,
    call_sign VARCHAR(255) NOT NULL,
    district VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    station_name VARCHAR(255) NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    time TIME NOT NULL,
    current_temp NUMERIC NOT NULL,
    dew_point_temp NUMERIC NOT NULL,
    rh NUMERIC NOT NULL,
    wind_direction NUMERIC NOT NULL,
    wind_speed NUMERIC NOT NULL,
    mslp NUMERIC NOT NULL,
    min_temp NUMERIC NOT NULL,
    max_temp NUMERIC NOT NULL,
    latitude NUMERIC NOT NULL,
    longitude NUMERIC NOT NULL,
    weather_code VARCHAR(255) NOT NULL,
    nebulosity NUMERIC NOT NULL,
    feel_like NUMERIC NOT NULL,
    rainfall_sel VARCHAR(255) NOT NULL,
    rainfall NUMERIC NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);